spring.application.name=workshop-service


spring.datasource.url=jdbc:postgresql://localhost:5433/workshopdb
spring.datasource.username=konrad
spring.datasource.password=konrad
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.security.oauth2.client.registration.google.client-id=1024165612190-0b6jj5b0qm3qmhls45ga0psdiifjc2lt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
